# Generated by Django 3.1.7 on 2021-03-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='boi',
            new_name='bio',
        ),
    ]
